language: go
go:
  - 1.12.x
  - master

sudo: false
os:
  - linux

before_script:
  - git submodule update --init --recursive
  - export GO111MODULE=on
script:
  - go build

before_deploy:
  - GOARCH=amd64 GOOS=linux   go build -o cryptoassets-linux-amd64
  - GOARCH=amd64 GOOS=windows go build -o cryptoassets-windows-amd64.exe
  - zip -r cryptoassets-linux-amd64.zip cryptoassets-linux-amd64 config.toml README.md
  - unix2dos config.toml README.md
  - zip -r cryptoassets-windows-amd64.zip cryptoassets-windows-amd64 config.toml README.md
  
# deploy:
#   provider: releases
#   skip_cleanup: true
#   local_dir: dist
#   github_token: $GITHUB_TOKEN
#   keep_history: true
#   file:
#   - cryptoassets-linux-amd64.zip
#   - cryptoassets-windows-386.zip
#   on:
#     tags: true
#     all_branches: true
#     go: 1.12

